#!/usr/bin/env node

import fs from 'fs';
import { execSync } from 'child_process';
import path from 'path';
import { fileURLToPath } from 'url';

// Get the directory name in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Get the latest commit message
try {
  const commitMessage = execSync('git log -1 --pretty=%B').toString().trim();
  
  // Extract version (text until the first space)
  const version = commitMessage.split(' ')[0];
  
  // Check if the version looks valid (starts with V or v followed by numbers and dots)
  if (!/^[Vv](\d+\.)*\d+$/.test(version)) {
    console.warn(`Warning: Extracted version "${version}" doesn't match expected format. Using as-is.`);
  }
  
  // Path to version.ts file
  const versionFilePath = path.join(__dirname, '..', 'src', 'version.ts');
  
  // Create or update the version.ts file
  const content = `// This file is automatically generated. Do not edit manually.
export const VERSION = '${version}';\n`;
  
  fs.writeFileSync(versionFilePath, content);
  
  console.log(`Version updated to ${version}`);
} catch (error) {
  console.error('Error updating version:', error.message);
  process.exit(1);
}
